from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()


@router.get("/journal", response_class=HTMLResponse)
def journal():
    return r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>FX · Trade Journal</title><style>
:root{color-scheme:dark;--bg:#090a0c;--surface:#101114;--raised:#17181c;--line:#292b31;--text:#f5f5f7;--muted:#9699a2;--accent:#fff;--good:#49cf8a;--bad:#ff6b72}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
button,select{font:inherit}.shell{min-height:100vh;display:grid;grid-template-columns:220px 1fr}.side{border-right:1px solid var(--line);padding:20px 14px;position:sticky;top:0;height:100vh}
.brand{font-size:19px;font-weight:760;letter-spacing:-.5px;margin:0 9px 28px}.brand span{color:var(--muted);font-weight:500}.nav{display:block;color:var(--muted);text-decoration:none;padding:10px;border-radius:8px;margin:2px 0}.nav:hover,.nav.active{background:var(--raised);color:var(--text)}
main{min-width:0;padding:30px 34px 70px}.head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px}.eyebrow{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.12em}h1{font-size:32px;letter-spacing:-1.3px;margin:7px 0 4px}p{color:var(--muted);margin:0}.filters{display:flex;gap:8px;flex-wrap:wrap}.select{background:var(--surface);color:var(--text);border:1px solid var(--line);padding:9px 12px;border-radius:8px}
.metrics{display:grid;grid-template-columns:repeat(5,minmax(125px,1fr));gap:10px;margin:28px 0}.metric{border:1px solid var(--line);background:var(--surface);padding:15px;border-radius:11px}.metric small{display:block;color:var(--muted);margin-bottom:8px}.metric b{font-size:21px}.tabs{display:flex;gap:4px;overflow:auto;border-bottom:1px solid var(--line)}.tab{border:0;background:none;color:var(--muted);padding:12px 10px;white-space:nowrap;cursor:pointer}.tab.active{color:var(--text);border-bottom:2px solid var(--accent)}
.table-wrap{overflow:auto;margin-top:14px;border:1px solid var(--line);border-radius:11px;background:var(--surface)}table{width:100%;border-collapse:collapse;min-width:1080px}th,td{text-align:left;padding:12px 13px;border-bottom:1px solid var(--line);font-size:12px}th{color:var(--muted);font-weight:550;position:sticky;top:0;background:var(--surface)}.empty{padding:55px;text-align:center;color:var(--muted)}.pill{border:1px solid var(--line);padding:3px 7px;border-radius:99px}.good{color:var(--good)}.bad{color:var(--bad)}
@media(max-width:900px){.shell{grid-template-columns:1fr}.side{height:auto;position:static;border-right:0;border-bottom:1px solid var(--line);display:flex;gap:5px;overflow:auto}.brand{margin:8px 15px 8px 4px}.nav{white-space:nowrap}main{padding:22px 16px}.head{align-items:flex-start;flex-direction:column}.metrics{grid-template-columns:repeat(2,1fr)}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
</style></head><body><div class="shell"><aside class="side"><div class="brand">FX <span>Terminal</span></div><a class="nav" href="/terminal">Chat & Markets</a><a class="nav" href="/terminal">Bots</a><a class="nav" href="/terminal">Training</a><a class="nav" href="/terminal">Campaigns</a><a class="nav active" href="/journal">Journal</a><a class="nav" href="/terminal">Settings</a></aside>
<main><header class="head"><div><div class="eyebrow">Local paper · canonical records</div><h1>Trade Journal</h1><p>Every protected trade, attributed to its bot and campaign.</p></div><div class="filters"><select id="bot" class="select" aria-label="Bot"><option value="">All bots</option></select><select id="mode" class="select" aria-label="Mode"><option>Local paper</option></select></div></header>
<section class="metrics" id="metrics"></section><div class="tabs" id="tabs"></div><div class="table-wrap"><table><thead><tr><th>Opened</th><th>Bot</th><th>Asset</th><th>Instrument</th><th>Side</th><th>Size</th><th>Entry</th><th>Exit</th><th>Stop</th><th>Net P&amp;L</th><th>Status</th></tr></thead><tbody id="rows"></tbody></table><div class="empty" id="empty">Loading verified trades…</div></div></main></div>
<script>
const classes=['All Trades','Forex','Commodities','Indices','Stocks','Crypto','ETFs','Futures'];let selected='';let data=[];
const money=v=>v===null||v===undefined?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);const num=v=>v===null||v===undefined?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:6});
function renderTabs(){const el=document.getElementById('tabs');el.replaceChildren();classes.forEach((name,i)=>{const value=i?name:'';const b=document.createElement('button');b.className='tab'+(selected===value?' active':'');b.textContent=name;b.onclick=()=>{selected=value;renderTabs();load()};el.appendChild(b)})}
function cell(row,value,cls){const td=document.createElement('td');td.textContent=value;cls&&(td.className=cls);row.appendChild(td)}
function renderRows(emptyMessage){const body=document.getElementById('rows'),empty=document.getElementById('empty');body.replaceChildren();empty.style.display=data.length?'none':'block';empty.textContent=emptyMessage||'No canonical trades match these filters.';data.forEach(t=>{const tr=document.createElement('tr');cell(tr,t.opened_at_display||'—');cell(tr,t.bot_id);cell(tr,t.asset_class);cell(tr,t.instrument);cell(tr,t.direction);cell(tr,num(t.quantity));cell(tr,num(t.entry_price));cell(tr,num(t.exit_price));cell(tr,num(t.stop));cell(tr,money(t.net_pnl),t.net_pnl>0?'good':t.net_pnl<0?'bad':'');cell(tr,t.status);body.appendChild(tr)})}
function metric(label,value){const d=document.createElement('div');d.className='metric';const s=document.createElement('small');s.textContent=label;const b=document.createElement('b');b.textContent=value;d.append(s,b);return d}
async function load(){const bot=document.getElementById('bot').value;const q=new URLSearchParams();selected&&q.set('asset_class',selected);bot&&q.set('bot_id',bot);const [trades,dash]=await Promise.all([fetch('/api/reporting/trades?'+q).then(r=>r.json()),fetch('/api/reporting/dashboard').then(r=>r.json())]);data=trades.trades||[];const m=dash.metrics;const legacy=Number(dash.account.positions||0)-Number(m.open_trades||0);const emptyMessage=legacy>0?'No verified canonical trades yet. '+legacy+' legacy positions remain visible in Paper Portfolio and are excluded from validated performance.':'No canonical trades match these filters.';renderRows(emptyMessage);const cards=document.getElementById('metrics');cards.replaceChildren(metric('Net P&L',money(m.net_pnl)),metric('Closed trades',m.closed_trades),metric('Win rate',m.win_rate===null?'Not available':(m.win_rate*100).toFixed(1)+'%'),metric('Profit factor',m.profit_factor===null?'Not available':m.profit_factor.toFixed(2)),metric('Open positions',dash.account.positions));const select=document.getElementById('bot');if(select.options.length===1)Object.keys(dash.by_bot||{}).forEach(id=>select.add(new Option(id,id)))}
document.getElementById('bot').onchange=load;renderTabs();load().catch(()=>{document.getElementById('empty').textContent='FX could not load the journal. Your local records were not changed.'});
</script></body></html>'''
